os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.14.1"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=10.14.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - secure: nB4jgqDZ15s6Uel4fNOvtWvUrMqGWzlwpHJHP5L91kFAv2m+1mB51WdBlnmMwIONZffH+NnERrtFar5Mw3tAfcfrRvSnlPALXIBdVtkajUAVtaPu5Og8ThzN166kBYmGZoyQumxI7snIsiLaowXg0XiCL+rNPbTopAy54JxYJz+MY9vsrZY4xDzVVA+DXyfxqvO2arFfAeaxheBwRsCbD0w5DeHoHQQyiA4eyVRE64n8vrR7Ao3rhfIr7en9kgEBF3xN9t5GSzwEMceaDXkDVXxs3TqKkrqBzOksPTZM8T1MMvjIqUj1qYsNGo9MpMLzupL3Y+zFsBelG1/B45U8CHbE6ltdXz6H2U1H1061KrW15jqod/oTB8tQr5eAhGTkqzQq6QbTAMNskaDJ/A2efXvNSEM9r712ipguRy+KV8ZYbR0TqEiBVDq3W+LD4gk8yCGY8rQqmGDN7WRe3t1bKyWWT4JY94QvGuQdPgWxaUEozUWKC5zBhIuMqbKb0igx5uXb5u21W/g8DDzanHqbb1ccZwJmDzF+HrNh9xs1F3Uv5xcbEDh5iW2omaGTQmpOOthW/AvotkKom2ds5ZuO3dC7bQPbfCIhSnT1IIK9dS1d0qiVMayJTRi4D+0WTxsA1hvY/tdGTtsKvACnMtoZ13BTGd23YEdwQYb8xMq0ZF8=
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x gradlew
  - ./gradlew clean test
  - ./gradlew npm_run_test -PnodeInstall --no-daemon
  - ./gradlew stage -Pprod -x test
 # - ./gradlew deployHeroku
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    #on_start: false     # default: false
